spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:7070/realms/PoultryFarmSystem # Keycloak Realm URL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chick_service?createDatabaseIfNotExist=true
    username: root
    password: testUser
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    baseline-description: "init"
#    baseline-version: 0
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}
server:
  port: 8030